# This is a basic workflow to help you get started with Actions

name: deploy-infra

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      AZURE_SUBSCRIPTION_ID:
        description: 'Subscription ID or Name'
        required: true
        type: string
      AZURE_AZURE_RESOURCEGROUP_NAME:
        description: 'Name of the Resource group'
        default: 'automate-confluence-func'
        required: false
        type: string

  # Allows you to run this workflow manually from the Actions tab
  # workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
         
          
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.6
        with:
          # Specify the script here
          inlineScript: |
            az account set -s ${{ inputs.AZURE_SUBSCRIPTION_ID }}
            groupexist=$(az group show -n ${{ inputs.AZURE_RESOURCEGROUP_NAME }}
            if [ -z "$groupexist" ]; then
            az group create -n ${{ inputs.AZURE_RESOURCEGROUP_NAME }} -l ${{ inputs.location}}
            fi
            az deployment group create -g ${{ inputs.AZURE_RESOURCEGROUP_NAME }} -f $GITHUB_WORKSPACE/infra/main.bicep
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          azcliversion: 2.30.0